wandb_version: 1
tokenizer:
  value: 'en_core_web_md'
vectors:
  value: 'en_core_web_md'
dataset:
  value: 'babi'
model:
  value: 'universal_transformer'
optimizer:
  value: 'adam'
epochs:
  value: 10
batch_size:
  value: 8
lr:
  value: 0.0001
log:
  value: null
learning_rate_decay_schedule:
  value: null
log_freq:
  value: null
checkpoint_metric:
  value: 'accuracy'
dataset.debug:
  value: False
dataset.task:
  value: 'all'
dataset.version:
  value: '1k'
