wandb_version: 1
undersample:
  value: True
tokenizer:
  value: 'en_core_web_md'
vectors:
  value: 'en_core_web_md'
dataset:
  value: 'babi'
model:
  value: 'vanilla'
optimizer:
  value: 'adam'
epochs:
  value: 20
batch_size:
  value: 8
seq_length_max:
  value: 100
train_size_max:
  value: 24
val_size_max:
  value: 24
lr:
  value: 0.0001
log:
  value: null
learning_rate_decay_schedule:
  value: null
log_freq:
  value: null
checkpoint_metric:
  value: 'loss'
dataset.bar:
  value: 'cow'
